### PR TITLE
Scm/equations

### PR DESCRIPTION
**Pull request by JorgeLuizFranco**
Added basic retrieval equations from CausalGraph generated.

For now, the regression is pure OLS, but we can make improvements. Also, we assume the input for retrieving the equations a SimpleDigraph(est_g in the examples) and a DataFrame, and return the variables and the corresponding coefficients ( linear relationships assumption).

### CODE REVIEW

**Comment by JorgeLuizFranco** [comment]
Expect and check if it is a DAG. Get residual of OLS. `x = coefficient[1] + scale[1]*randn()`.  Parameter `::AbstractMatrix` use Tables.jl. SCM should also return the DAG.

**Comment by mschauer** [comment]
A couple of todo's:

[ ] include the file in CausalInference.jl
[ ] figure out if you really need DataFrames, and if so, add it to the project
[ ] write a simple test making sure the code runs.

**Comment by JorgeLuizFranco** [comment]
> A couple of todo's:
> 
> [ ] include the file in CausalInference.jl [ ] figure out if you really need DataFrames, and if so, add it to the project [ ] write a simple test making sure the code runs.

Done, Moritz

**Comment by mschauer** [comment]
Ah great, that is taking shape. Can you uncommit the changes to the yaml files?

**Comment by JorgeLuizFranco** [comment]
I think everything now is as requested @mschauer

**Comment by JorgeLuizFranco** [comment]
Closes #154

**Pull request merged**
