### PR TITLE
Causal Zig-Zag

### PR DESCRIPTION
**Pull request by mschauer**

### CODE REVIEW

**Comment by mschauer** [comment]
Sporadic test error
```
Test Summary:        |   Pass   Total  Time
operators randgraphs | 150000  150000  0.6s
nextCPDAG randgraphs: Error During Test at /Users/smoritz/.julia/dev/CausalInference/test/operators.jl:112
  Got exception outside of a @test
  ArgumentError: collection must be non-empty
  Stacktrace:
    [1] SamplerRangeNDL
      @ /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Random/src/generation.jl:333 [inlined]
    [2] Sampler
      @ /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Random/src/generation.jl:189 [inlined]
    [3] Sampler
      @ /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Random/src/generation.jl:418 [inlined]
    [4] Sampler
      @ /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Random/src/Random.jl:139 [inlined]
    [5] rand
      @ /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Random/src/Random.jl:255 [inlined]
    [6] rand
      @ /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Random/src/Random.jl:260 [inlined]
    [7] macro expansion
      @ ~/.julia/dev/CausalInference/test/operators.jl:128 [inlined]
    [8] macro expansion
      @ /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Test/src/Test.jl:1577 [inlined]
    [9] top-level scope
      @ ~/.julia/dev/CausalInference/test/operators.jl:113
   [10] include(fname::String)
      @ Base.MainInclude ./client.jl:489
   [11] top-level scope
      @ ~/.julia/dev/CausalInference/test/runtests.jl:5
   [12] include(fname::String)
      @ Base.MainInclude ./client.jl:489
   [13] top-level scope
      @ none:6
   [14] eval
      @ Core ./boot.jl:383 [inlined]
   [15] exec_options(opts::Base.JLOptions)
      @ Base ./client.jl:291
   [16] _start()
      @ Base ./client.jl:552
Test Summary:        | Pass  Error  Total  Time
nextCPDAG randgraphs |   56      1     57  3.6s
ERROR: LoadError: Some tests did not pass: 56 passed, 0 failed, 1 errored, 0 broken.
in expression starting at /Users/smoritz/.julia/dev/CausalInference/test/operators.jl:112
in expression starting at /Users/smoritz/.julia/dev/CausalInference/test/runtests.jl:5
ERROR: Package CausalInference errored during testing
```

**Comment by mwien** [comment]
> Sporadic test error
> 
> ```
> Test Summary:        |   Pass   Total  Time
> operators randgraphs | 150000  150000  0.6s
> nextCPDAG randgraphs: Error During Test at /Users/smoritz/.julia/dev/CausalInference/test/operators.jl:112
>   Got exception outside of a @test
>   ArgumentError: collection must be non-empty
>   Stacktrace:
>     [1] SamplerRangeNDL
>       @ /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Random/src/generation.jl:333 [inlined]
>     [2] Sampler
>       @ /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Random/src/generation.jl:189 [inlined]
>     [3] Sampler
>       @ /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Random/src/generation.jl:418 [inlined]
>     [4] Sampler
>       @ /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Random/src/Random.jl:139 [inlined]
>     [5] rand
>       @ /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Random/src/Random.jl:255 [inlined]
>     [6] rand
>       @ /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Random/src/Random.jl:260 [inlined]
>     [7] macro expansion
>       @ ~/.julia/dev/CausalInference/test/operators.jl:128 [inlined]
>     [8] macro expansion
>       @ /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Test/src/Test.jl:1577 [inlined]
>     [9] top-level scope
>       @ ~/.julia/dev/CausalInference/test/operators.jl:113
>    [10] include(fname::String)
>       @ Base.MainInclude ./client.jl:489
>    [11] top-level scope
>       @ ~/.julia/dev/CausalInference/test/runtests.jl:5
>    [12] include(fname::String)
>       @ Base.MainInclude ./client.jl:489
>    [13] top-level scope
>       @ none:6
>    [14] eval
>       @ Core ./boot.jl:383 [inlined]
>    [15] exec_options(opts::Base.JLOptions)
>       @ Base ./client.jl:291
>    [16] _start()
>       @ Base ./client.jl:552
> Test Summary:        | Pass  Error  Total  Time
> nextCPDAG randgraphs |   56      1     57  3.6s
> ERROR: LoadError: Some tests did not pass: 56 passed, 0 failed, 1 errored, 0 broken.
> in expression starting at /Users/smoritz/.julia/dev/CausalInference/test/operators.jl:112
> in expression starting at /Users/smoritz/.julia/dev/CausalInference/test/runtests.jl:5
> ERROR: Package CausalInference errored during testing
> ```

Should be fixed by https://github.com/mschauer/CausalInference.jl/pull/119/commits/5547c8305479043a91a40b437982689d2f8e4c48

**Comment by mwien** [comment]
🥳

**Comment by mschauer** [comment]
https://github.com/mschauer/CausalInference.jl/blob/master/docs/src/examples/ges_basic_examples.md

**Pull request merged**
